config/routes.rb
Rails.application.routes.draw do

# 管理側
  namespace :admin do
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    root 'homes#top'
  end

# 顧客側
 scope module: :public do
   root to: 'homes#top'
   get '/about' => 'homes#about'
   resources :items, only: [:index, :show]
   resources :destinations, only: [:index, :edit, :create, :update, :destroy]
   resources :cart_items, only: [:index, :update, :create, :destroy] do
     collection do #collectionはresourcesの中だとしてもidをpathから取り除ける
     delete 'destroy_all' => 'cart_items#destroy_all'
     end
   end
   resource :customers,only: [] do #resourceはidとindexをpathから取り除ける
     get 'my_page' => 'customers#show'
     get 'information/edit' => 'customers#edit'
     patch 'information' => 'customers#update'
     get 'unsubscribe' =>'customers#unsubscribe'
     patch 'withdraw' => 'customers#withdraw'
   end
   resources :orders,only: [:index, :new, :show, :create] do
     collection do
     post 'payment_method' => 'orders#payment_method' #これなんだっけ（テーブル定義書にはない）
     post 'confirm' => 'orders#confirm'
     get 'thanks' => 'orders#thanks'
     end
   end
 end



devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  validates :count, presence: true


  def add_tax_price
  (item.price * 1.10).round
  end

  def subtotal
    item.add_tax_price * count.to_i
  end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :orders
  has_many :destinations
  has_many :cart_items
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # フルネームメソッド　selfはcustomerモデルのことを
  def full_name
    self.family_name + " " + self.personal_name
  end
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :customer

  validates :address, presence: true
  validates :postcode, presence: true
  validates :name, presence: true

  def address_display
    '〒' + postcode.to_s + ' ' + address.to_s + ' ' + name.to_s
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many   :order_details
  has_many   :cart_item
  has_one_attached :image

  #バリデーション
  validates :image, presence: true
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true

  def get_image(width,height)
      image.variant(resize_to_limit: [width,height]).processed
  end

  #税込み価格を表示するための記述です。
  #add_tax_(消費税を計算したいカラム名)
  def add_tax_price
  (self.price * 1.10).round
  end
  
  def subtotal
  item.add_tax_price * count
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many   :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_for_payment: 0, payment_confirmation: 1, in_production: 2, preparing_for_shipment: 3, shipped: 4 }

  def get_image(width,height)
     image.variant(resize_to_limit: [width,height]).processed
  end

  def add_tax_price
    (item.price*1.10).round
  end

  def subtotal
    item.add_tax_price * item_count
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { no_production: 0,
                        waiting_production: 1,
                        in_production: 2,
                        completion_production: 3
  }

  def subtotal
    tax_price * item_count
  end

  private

  def order_detail_params
    params.require(:order_detail).permit(:making_status)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre=Genre.new
    @genres=Genre.all
  end

  def create
    @genre=Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    end
  end

  def update
    @genre=Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    end
  end

  def edit
    @genre=Genre.find(params[:id])
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    #1ページ分の決められた数のデータだけを、新しい順に取得する
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

 private

  def item_params
    params.require(:item).permit(:name, :image, :description, :genre_id, :price, :is_active )
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  
  def show
    @order = Order.find(params[:id])
    @total = 0
    @order.order_details.each do |detail|
      @total = @total+detail.subtotal
    end
  end

  def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
    # 注文ステータスが入金確認になると製作ステータスが全て製作中に変わる
    if @order.update(order_params)
      @order_details.update_all(making_status: 1) if @order.status == "payment_confirmation"
    end
    redirect_to admin_order_path(@order)
  end

  private
    def order_params
      params.require(:order).permit(:status)
    end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
before_action :configure_permitted_parameters, if: :devise_controller?
  
  
  
protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name, :personal_name, :family_name_ruby, :personal_name_ruby, :email, :postcode, :address, :telephone_number])
                
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end
  

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 mx-auto">
      <h4 class="my-4"><mark class="bg-light">ジャンル編集</h4>
      <%= form_with model: @genre, url: admin_genre_path do |f| %>
      <div class="col-auto my-5 form-inline">
        <label class="font-weight-bold">ジャンル名</label>
        <%= f.text_field :name ,class: "form-control mx-5" %>
        <%= f.submit "変更を保存" ,class: "btn btn-success" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 mx-auto">
      <h4 class="my-4"><mark class="bg-light">ジャンル一覧・追加</mark></h4>
      <!--追加-->
      <%= form_with model: @genre, url: admin_genres_path do |f| %>
      <div class="col-auto my-5 form-inline">
        <label class="font-weight-bold">ジャンル名</label>
        <%= f.text_field :name ,class: "form-control mx-5" %>
        <%= f.submit "新規登録" ,class: "btn btn-success" %>
      </div>
      <% end %>
      <!--一覧-->
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>ジャンル</th>
            <th></th>
          </tr>
        </thead>
        <% @genres.each do |genre| %>
        <tbody>
          <tr>
            <td><%= genre.name %></td>
            <td><%=link_to "編集する", edit_admin_genre_path(genre.id) ,class: "btn btn-success" %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/_error_messages.html.erb
<% if item.errors.any? %>
<div class="alert alert-warning badge-danger" role="alert">
  <h4>◆エラーが発生しました。入力内容を確認してください◆</h4>
  <ul>
    <% item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  </div>
<% end %>

app/views/admin/items/edit.html.erb
<div class='container add-font'>
  <div class='row'>
    <div class="col-md-8 mx-auto my-5">
    <%= render 'error_messages', item: @item %>
      <h3 class="my-5"><mark class="bg-light">商品編集</mark></h3>
        <div class="ml-3">
          <div class="mb-5 px-3">
          <%= form_with model: @item, url: admin_item_path, method: :patch do |f| %>
            <div class="row form-group">
              <h5 class="col-4">商品画像</h5>
              <%= f.file_field :image, accept: "image/*" %>
            </div>
            <div class="row form-group">
              <h5 class="col-4">商品名</h5>
              <%= f.text_field :name, placeholder: "商品名", class: "col-7 form-control" %>
            </div>
            <div class="row form-group">
              <h5 class="col-4">商品説明</h5>
              <%= f.text_area :description, placeholder: "ここに説明文を記述します", class: "col-7 form-control" %>
            </div>
            <!-- genreモデルに格納しているデータをプルダウンで選択してItemモデルに保存する-->
            <!--:保存カラム(ジャンルID),ジャンルすべて(Genre.all),保存する参照先カラム(ジャンルID),表示する参照先カラム(ジャンル名) -->
            <div class="row form-group">
              <h5 class="col-4">ジャンル</h5>
              <%= f.collection_select :genre_id,Genre.all,:id,:name, include_blank: "--選択してください--", class: "col-7 form-control" %>
            </div>
            <div class="row form-group">
              <h5 class="col-4">税抜価格</h5>
              <%= f.text_field :price, placeholder: "1000", class: "col-7 form-control" %>  円
            </div>
            <div class="row form-group">
              <h5 class="col-4">販売ステータス</h5>
                <div class="col-2">
                  <%= f.radio_button :is_active, true %>
                  <%= f.label :is_active_true, "販売中" %>
                </div>
                <div class="col-3">
                  <%= f.radio_button :is_active, false %>
                  <%= f.label :is_active_false, "販売停止中" %>
                </div>
            </div>
            <div class="text-center">
              <%= f.submit '  変更を保存  ', class: "btn btn-outline-success" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container add-font">
  <div class="row-4">
    <div class="col-md-10 mx-auto my-5">
      <h2 class="m-0"><mark class="bg-light">商品一覧</mark></h2>

        <!-- 新規登録ボタン-->
        <div class="text-right mr-2">
           <%= link_to new_admin_item_path, class: "btn btn-lg btn-{themecolor}.rounded-circle.p-0 secondary " do %>
             <i class="fas fa-plus-circle"></i>
           <% end %>
        </div>

        <table class="table text-senter">
          <thead class="thead-light">
            <tr class=>
              <th class="col-md-2 text-center">商品ID</th>
              <th class="col-md-4 text-left">商品名</th>
              <th class="col-md-2 text-center">税抜価格</th>
              <th class="col-md-2 text-center">ジャンル</th>
              <th class="col-md-2 text-center">ステータス</th>
            </tr>
          </thead>

          <% @items.each do |item| %>
          <tbody>
            <tr>
              <td class="text-center p-2"><%= item.id %></td>
              <td class="text-left p-2">
                <%= link_to admin_item_path(item), class: "text-reset", style: "text-decoration: black underline" do %>
                  <%= item.name %>
                <% end %>
              </td>
              <td class="text-center p-2"><%= item.price.to_s(:delimited) %></td>
              <td class="text-center p-2"><%= item.genre.name %></td>
              <td class="text-center p-2">
                <% if item.is_active == true %>
                  <p class="font-weight-bold text-success">販売中</p>
                <% else %>
                  <p class="font-weight-bold text-secondary">販売停止中</p>
                <% end %>
              </td>
            </tr>
          </tbody>
          <% end %>

        </table>
        <div class="col-2 mx-auto">
          <%= paginate @items %>
        </div>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class='container add-font'>
  <div class='row'>
    <div class="col-md-8 mx-auto my-5">
    <%= render 'error_messages', item: @item %>
      <h3 class="my-5"><mark class="bg-light">商品新規登録</mark></h3>
        <div class="ml-3">
          <div class="mb-5 px-3">
          <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
            <div class="row form-group">
              <h5 class="col-4">商品画像</h5>
              <%= f.file_field :image, accept: "image/*" %>
            </div>
            <div class="row form-group">
              <h5 class="col-4">商品名</h5>
              <%= f.text_field :name, placeholder: "商品名", class: "col-7 form-control" %>
            </div>
            <div class="row form-group">
              <h5 class="col-4">商品説明</h5>
              <%= f.text_area :description, placeholder: "ここに説明文を記述します", class: "col-7 form-control" %>
            </div>
            <!-- genreモデルに格納しているデータをプルダウンで選択してItemモデルに保存する-->
            <!--:保存カラム(ジャンルID),ジャンルすべて(Genre.all),保存する参照先カラム(ジャンルID),表示する参照先カラム(ジャンル名) -->
            <div class="row form-group">
              <h5 class="col-4">ジャンル</h5>
              <%= f.collection_select :genre_id,Genre.all,:id,:name, include_blank: "--選択してください--", class: "col-7 form-control" %>
            </div>
            <div class="row form-group">
              <h5 class="col-4">税抜価格</h5>
              <%= f.text_field :price, placeholder: "1000", class: "col-7 form-control" %>  円
            </div>
            <div class="row form-group">
              <h5 class="col-4">販売ステータス</h5>
                <div class="col-2">
                  <%= f.radio_button :is_active, true %>
                  <%= f.label :is_active_true, "販売中" %>
                </div>
                <div class="col-3">
                  <%= f.radio_button :is_active, false %>
                  <%= f.label :is_active_false, "販売停止中" %>
                </div>
            </div>
            <div class="text-center">
              <%= f.submit '  新規登録  ', class: "btn btn-outline-success" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class='container add-font'>
  <div class='row'>
    <div class="col-md-8 mx-auto my-2">
      <h2 class="my-5"><mark class="bg-light">商品詳細</mark></h2>
      <div class='row'>
        <div class="col-md-6 mx-auto">
          <%= image_tag @item.get_image(280,300) %>
        </div>
        <div class="col-md-6 mx-auto">
          <h5>| 商品名</h5>
            <p><%= @item.name %></p>
          <h5>| 商品説明</h5>
            <p><%= @item.description %></p>
          <h5>| ジャンル</h5>
            <p><%= @item.genre.name %></p>
           <!-- モデルに記述したadd_tax_priceメソッドを使用して税込価格を表示 -->
             <!-- (:dalimited)は数値を3桁区切りにしてくれる(ex:1,234円) -->
          <h5>| 税抜価格（税込価格）</h5>
            <p><%= @item.price.to_s(:delimited) %> ( <%= @item.add_tax_price.to_s(:delimited) %> )円</p>
           <!-- もしステータスがtrueであれば販売中を返し、そうでなければ販売停止中を返す -->
          <h5>| 販売ステータス</h5>
          <div>
            <% if @item.is_active == true %>
              <p class="font-weight-bold text-success">販売中</p>
            <% else %>
              <p class="font-weight-bold text-secondary">販売停止中</p>
            <% end %>
          </div>
        </div>
      </div>
        <div class="col-12 text-center mt-4">
          <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-outline-success" %>
        </div>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="col-auto">
    <h4 class="my-4"><mark class="bg-light">注文履歴詳細</mark></h4>
    <div class="row col-auto">
      <p class="font-weight-bold" style="width:20%">購入者</p>
      <%= link_to admin_customer_path(@order.customer), class:'text-reset', style:"text-decoration: underline" do %>
        <%= @order.customer.full_name %>
      <% end %>
    </div>
    <div class="row col-auto">
      <p class="font-weight-bold" style="width:20%">注文日</p>
      <%= @order.created_at.strftime("%Y/%m/%d ") %>
    </div>
    <div class="row mb-2 col-auto">
      <p class="font-weight-bold" style="width:20%">配送先</p>
      <%= "〒"+@order.ship_postcode.to_s+" "+@order.ship_address %><br>
      <%= @order.ship_name %>
    </div>
    <div class="row col-auto">
      <p class="font-weight-bold" style="width:20%">支払方法</p>
      <%= @order.payment_method_i18n %>
    </div>
    <div class="row col-auto">
      <p class="font-weight-bold" style="width:20%">注文ステータス</p>
      <%= form_with model: @order, url: admin_order_path, method: :patch do |f| %>
        <%= f.select :status, [["入金待ち","waiting_for_payment"],
                               ["入金確認","payment_confirmation"],
                               ["製作中","in_production"],
                               ["発送準備中","preparing_for_shipment"],
                               ["発送済み","shipped"]] %>
        <%= f.submit "更新", class:'btn btn-success' %>
      <% end %>
    </div>
  </div>
  <div class="d-flex">
    <table class="table">
      <thead>
        <tr>
          <th>商品名</th>
          <th>単価(税込)</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @order.order_details.each do |detail| %>
        <tr>
          <td>
            <%= detail.item.name %>
          </td>
          <td>
            <%= detail.tax_price %>
          </td>
          <td>
            <%= detail.item_count %>
          </td>
          <td>
            <%= detail.subtotal %>
          </td>
          <td>
            <%= form_with model: detail, url: admin_order_detail_path(detail), method: :patch do |f| %>
              <%= f.select :making_status, [["着手不可","no_production"],
                                            ["製作待ち","waiting_production"],
                                            ["製作中","in_production"],
                                            ["製作完了","completion_production"]] %>
              <%= f.hidden_field :order_id ,:value=> @order.id %>
              <%= f.submit "更新", class:'btn btn-success' %>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <div class="d-flex">
      <div class="col-auto">
        <p class="font-weight-bold">商品合計</p>
        <p class="font-weight-bold">送料</p>
        <p class="font-weight-bold">請求金額合計</p>
      </div>
      <div class="col-auto">
        <p class="text-right"><%= @total.to_s(:delimited)+"円" %></p>
        <p class="text-right"><%= 800.to_s(:delimited)+"円" %></p>
        <p class="text-right"><%= @order.charge.to_s(:delimited)+"円" %></p>
      </div>
    </div>

  </div>
</div>