config/routes.rb
Rails.application.routes.draw do

# 管理側
  namespace :admin do
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    root 'homes#top'
  end

# 顧客側
 scope module: :public do
   root to: 'homes#top'
   get '/about' => 'homes#about'
   resources :items, only: [:index, :show]
   resources :destinations, only: [:index, :edit, :create, :update, :destroy]
   resources :cart_items, only: [:index, :update, :create, :destroy] do
     collection do #collectionはresourcesの中だとしてもidをpathから取り除ける
     delete 'destroy_all' => 'cart_items#destroy_all'
     end
   end
   resource :customers,only: [] do #resourceはidとindexをpathから取り除ける
     get 'my_page' => 'customers#show'
     get 'information/edit' => 'customers#edit'
     patch 'information' => 'customers#update'
     get 'unsubscribe' =>'customers#unsubscribe'
     patch 'withdraw' => 'customers#withdraw'
   end
   resources :orders,only: [:index, :new, :show, :create] do
     collection do
     post 'payment_method' => 'orders#payment_method' #これなんだっけ（テーブル定義書にはない）
     post 'confirm' => 'orders#confirm'
     get 'thanks' => 'orders#thanks'
     end
   end
 end



devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  validates :count, presence: true


  def add_tax_price
  (item.price * 1.10).round
  end

  def subtotal
    item.add_tax_price * count.to_i
  end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :orders
  has_many :destinations
  has_many :cart_items
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # フルネームメソッド　selfはcustomerモデルのことを
  def full_name
    self.family_name + " " + self.personal_name
  end
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :customer

  validates :address, presence: true
  validates :postcode, presence: true
  validates :name, presence: true

  def address_display
    '〒' + postcode.to_s + ' ' + address.to_s + ' ' + name.to_s
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many   :order_details
  has_many   :cart_item
  has_one_attached :image

  #バリデーション
  validates :image, presence: true
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true

  def get_image(width,height)
      image.variant(resize_to_limit: [width,height]).processed
  end

  #税込み価格を表示するための記述です。
  #add_tax_(消費税を計算したいカラム名)
  def add_tax_price
  (self.price * 1.10).round
  end
  
  def subtotal
  item.add_tax_price * count
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many   :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_for_payment: 0, payment_confirmation: 1, in_production: 2, preparing_for_shipment: 3, shipped: 4 }

  def get_image(width,height)
     image.variant(resize_to_limit: [width,height]).processed
  end

  def add_tax_price
    (item.price*1.10).round
  end

  def subtotal
    item.add_tax_price * item_count
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { no_production: 0,
                        waiting_production: 1,
                        in_production: 2,
                        completion_production: 3
  }

  def subtotal
    tax_price * item_count
  end

  private

  def order_detail_params
    params.require(:order_detail).permit(:making_status)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    #1ページ分の決められた数のデータだけを、新しい順に取得する
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

 private

  def item_params
    params.require(:item).permit(:name, :image, :description, :genre_id, :price, :is_active )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
before_action :configure_permitted_parameters, if: :devise_controller?
  
  
  
protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name, :personal_name, :family_name_ruby, :personal_name_ruby, :email, :postcode, :address, :telephone_number])
                
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end
  

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer class="fixed-bottom alert-danger text-center text-secondary ">
  <div class="container align-items-end ">
    <div class="mx-auto p-2">
       © 2023 ke-tora
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="alert-danger shadow-sm p-1">
  <nav class="navbar navbar-expand-lg navbar-light text-right">
    <div class="container mr-0">
      <a class="navbar-brand" href="/"><%= image_tag("logo.png") %></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">

          <!--管理者側がログインしている時＋２つのアカウントでのログインを許容する -->
          <% if admin_signed_in? %>
            <% if request.fullpath.include? "/admin" %>
              <li class="nav-item text-dark">
                <%= link_to "商品一覧", admin_items_path, class: 'btn btn-outline-secondary mb-3' %>
              </li>
              <li class="nav-item">
                <%= link_to "会員一覧", admin_customers_path, class: 'btn btn-outline-secondary ml-3 mb-3' %>
              </li>
              <li class="nav-item">
                <%= link_to "注文履歴一覧", admin_root_path, class: 'btn btn-outline-secondary ml-3 mb-3' %>
              </li>
              <li class="nav-item">
                <%= link_to "ジャンル一覧", admin_genres_path, class: 'btn btn-outline-secondary ml-3 mb-3' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'btn btn-outline-secondary ml-3' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "マイページ", my_page_customers_path(current_customer), class: 'btn btn-outline-secondary mb-3' %>
              </li>
              <li class="nav-item">
                <%= link_to "商品一覧", items_path, class: 'btn btn-outline-secondary ml-3 mb-3' %>
              </li>
              <li class="nav-item">
                <%= link_to "カート", cart_items_path, class: 'btn btn-outline-secondary ml-3 mb-3' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'btn btn-outline-secondary ml-3' %>
              </li>
            <% end %>

            <!--顧客側がログインしている時 -->
          <% elsif customer_signed_in? %>
            <li>
              <p class="nav-link text-dark mr-5">ようこそ、<%= current_customer.family_name %>さん！</p>
            </li>
            <li>
            <li class="nav-item">
              <%= link_to "マイページ", my_page_customers_path(current_customer), class: 'btn btn-outline-secondary mb-3' %>
            </li>
            <li class="nav-item">
              <%= link_to "商品一覧", items_path, class: 'btn btn-outline-secondary ml-3  mb-3' %>
            </li>
            <li class="nav-item">
              <%= link_to "カート", cart_items_path, class: 'btn btn-outline-secondary ml-3 mb-3' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'btn btn-outline-secondary ml-3' %>
            </li>

            <!--ログインしていない時 -->
          <% else %>
            <li class="nav-item">
              <%= link_to "About", about_path, class: 'btn btn-outline-secondary mb-3' %>
            </li>
            <li class="nav-item">
              <%= link_to "商品一覧", items_path, class: 'btn btn-outline-secondary ml-3 mb-3' %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", new_customer_registration_path, class: 'btn btn-outline-secondary ml-3 mb-3' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_customer_session_path, class: 'btn btn-outline-secondary ml-3' %>
            </li>
          <% end %>
          </ul>
        </div>
      </div>

      <!--検索窓（実際に検索はできません） -->
      <div class="search_form">
        <% if admin_signed_in? %>
          <%= form_with url: admin_root_path, method: :get do |f| %>
            <div class="input-group mb-3">
              <%= f.text_field :word, class: "form-control search-control mr-1", placeholder: "Search..." %>
              <%= button_tag type: "submit", class: "btn btn-light search-btn " do %>
            <i class="fas fa-search"></i>
              <% end %>
          <% end %>
        <% else %>
          <%= form_with url: root_path, method: :get do |f| %>
            <div class="input-group mb-3">
              <%= f.text_field :word, class: "form-control search-control mr-1", placeholder: "Search..." %>
              <%= button_tag type: "submit", class: "btn btn-light " do %>
                <i class="fas fa-search"></i>
              <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <%= render 'layouts/header' %>
    <main>
    <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>